### ISSUE TITLE
Multiple past versions of Maploom js and css are getting build even after purge

### ISSUE THREAD

**Issue by JJediny** [ROGUE-JCTD/django-maploom#1]
# Purged django-maploom from system, rebuilt using following
## Post collectstatic getting the following static files generated

(venvuser)root@ip:/var/lib/geonode/rogue_geonode# locate maploom

```
/opt/rogue-scripts/test-modules/test-module-maploom.js
/var/lib/geonode/lib/python2.7/site-packages/django-maploom.egg-link
/var/lib/geonode/lib/python2.7/site-packages/django_maploom-1.0.0-py2.7.egg-info
/var/lib/geonode/lib/python2.7/site-packages/maploom
/var/lib/geonode/rogue_geonode/geoshape/templates/maps/maploom.html
/var/www/rogue/maploom
/var/www/rogue/maploom/assets
/var/www/rogue/maploom/fonts
/var/www/rogue/maploom/assets/MapLoom-1.0.0.css
/var/www/rogue/maploom/assets/MapLoom-1.0.0.js
/var/www/rogue/maploom/assets/MapLoom-1.0.0.js.20141111
/var/www/rogue/maploom/assets/MapLoom-1.0.0.js.20141112
/var/www/rogue/maploom/assets/MapLoom-1.1.css
/var/www/rogue/maploom/assets/MapLoom-1.1.js
/var/www/rogue/maploom/assets/README.md
/var/www/rogue/maploom/assets/angular-sanitize.1.2.21.js
/var/www/rogue/maploom/assets/error.png
/var/www/rogue/maploom/assets/error.svg
/var/www/rogue/maploom/assets/loading.gif
/var/www/rogue/maploom/assets/play-pause.png
/var/www/rogue/maploom/assets/play-pause.svg
/var/www/rogue/maploom/assets/video-play.png
/var/www/rogue/maploom/assets/video-play.svg
/var/www/rogue/maploom/fonts/glyphicons-halflings-regular.eot
/var/www/rogue/maploom/fonts/glyphicons-halflings-regular.svg
/var/www/rogue/maploom/fonts/glyphicons-halflings-regular.ttf
/var/www/rogue/maploom/fonts/glyphicons-halflings-regular.woff
```

**Comment by garnertb** [comment]
Can you try including the `--clear` switch when you run `collectstatic`?  I double-checked and neither the 1.0 package nor the 1.1.1 package includes multiple versions.  

Finally, while it isn't ideal to have multiple versions of the application it shouldn't have any negative  impact since `/var/lib/geonode/rogue_geonode/geoshape/templates/maps/maploom.html` is pegged to one or the other.

**Comment by JJediny** [comment]
think the error was that the file cached in the web browser combined with manually deleting the old static files as I first didn't use the --clear option for (python manage.py collectstatic) when upgrading. The strange part though was even after clearing the web browser cache and restarting nginx, with the old .js and .css still available on the www static maploom was loading the 1.0 version; only after manually deleting them (or using --clear) did it switch to using the newer files
