### ISSUE TITLE
trouble installing maploom with GeoNode 2.4

### ISSUE THREAD

**Issue by d3netxer** [ROGUE-JCTD/django-maploom#3]
I am getting the error below after trying to follow installation instructions. Any help?

ReferenceError: goog is not defined
http://localhost/maploom/maps/new?layer=geonode%3Aper_adm1
Line 51

**Comment by garnertb** [comment]
Can you inspect the network traffic and post the versions of Maploom you are using?

**Comment by d3netxer** [comment]
yes, it says this in the html tab in firebug:

```
<head>
<title ng-bind="pageTitle"></title>
<script type="text/javascript">
<link href="/static/maploom/assets/MapLoom-1.5.0.css" type="text/css" rel="stylesheet">
<script src="/static/maploom/assets/MapLoom-1.5.0.js" type="text/javascript">
<script type="text/javascript">
</head>
```

**Comment by garnertb** [comment]
Can you confirm in the network tab that you're not getting any 404s?

Specifically make sure that `/static/maploom/assets/MapLoom-1.5.0.js` exists.  If not you may need to do a `python manage.py collectstatic`.

**Comment by d3netxer** [comment]
wow, amazing, collectstatic did the trick! Thanks!
